- name: Shell Linter
  # You may pin to the exact commit or the version.
  # uses: azohra/shell-linter@c7ec10122c585f8687a4231d4beb06fb8ed777fe
  uses: azohra/shell-linter@v0.4.0
  with:
    # Execute lint check on a specific file or folder.
    path: # optional, default is .
    # Specify minimum severity of errors to consider.
    severity: # optional, default is style
